### ISSUE TITLE
NPlayer exception thrown

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1182]
The following exception was thrown on the production server and should be fixed. A test should also be added for this functionality

```
6|netsblox | [ERROR] TypeError: Cannot read property 'role' of undefined
6|netsblox |     at NPlayer.endTurn (/home/ubuntu/netsblox/src/server/rpc/procedures/n-player/n-player.js:94:79)
6|netsblox |     at RPCManager.handleRPCRequest (/home/ubuntu/netsblox/src/server/rpc/rpc-manager.js:171:30)
6|netsblox |     at Layer.handle [as handle_request] (/home/ubuntu/netsblox/node_modules/express/lib/router/layer.js:95:5)
6|netsblox |     at next (/home/ubuntu/netsblox/node_modules/express/lib/router/route.js:137:13)
6|netsblox |     at Route.dispatch (/home/ubuntu/netsblox/node_modules/express/lib/router/route.js:112:3)
6|netsblox |     at Layer.handle [as handle_request] (/home/ubuntu/netsblox/node_modules/express/lib/router/layer.js:95:5)
6|netsblox |     at /home/ubuntu/netsblox/node_modules/express/lib/router/index.js:281:22
6|netsblox |     at param (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:354:14)
6|netsblox |     at param (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:365:14)
6|netsblox |     at Function.process_params (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:410:3)
6|netsblox |     at next (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:275:10)
6|netsblox |     at Function.handle (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:174:3)
6|netsblox |     at router (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:47:12)
6|netsblox |     at Layer.handle [as handle_request] (/home/ubuntu/netsblox/node_modules/express/lib/router/layer.js:95:5)
6|netsblox |     at trim_prefix (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:317:13)
6|netsblox |     at /home/ubuntu/netsblox/node_modules/express/lib/router/index.js:284:7
6|netsblox |     at Function.process_params (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:335:12)
6|netsblox |     at next (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:275:10)
6|netsblox |     at /home/ubuntu/netsblox/src/server/server.js:69:9
6|netsblox |     at Layer.handle [as handle_request] (/home/ubuntu/netsblox/node_modules/express/lib/router/layer.js:95:5)
6|netsblox |     at trim_prefix (/home/ubuntu/netsblox/node_modules/express/lib/router/index.js:317:13)
6|netsblox |     at /home/ubuntu/netsblox/node_modules/express/lib/router/index.js:284:7
```

**Comment by hamidzr** [comment]
I'm adding a guard against this but how do I reproduce the bug ?

**Comment by brollb** [comment]
This is pretty old and no longer relevant.
