### ISSUE TITLE
failing tests on Travis

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1615]
tests are failing on Travis

```
1) projects should create copy if name changed after persist:
     TypeError: Cannot read property 'roles' of null
      at clean (src/server/storage/projects.js:38:21)
      at _db.findOne.then.project (src/server/storage/projects.js:80:21)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  2) projects should have the correct origin time:
      AssertionError: 1508287821480 == 1508287821501
      + expected - actual
      -1508287821480
      +1508287821501
      
      at project.getRawProject.then.data (test/server/storage/projects.js:138:24)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by brollb** [comment]
The tests are currently passing but this is something we should keep an eye out for
