### ISSUE TITLE
failing build on travis

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1719]
```
1) active-room updating the name should append number to name if colliding with existing:
      AssertionError: 'proj-1512071169693' != 'proj-1512071169693'
      + expected - actual
      
      at createRoom.then.then.then (test/server/rooms/active-room.spec.js:522:28)
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
  2) active-room updating the name persisted should not duplicate project if inPlace:
     TypeError: Cannot read property 'roles' of null
      at clean (src/server/storage/projects.js:9:1730)
      at _db.findOne.then.project (src/server/storage/projects.js:9:3934)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by brollb** [comment]
This appears to be a nondeterministic failure... I suspect there might be a race condition somewhere that needs to be hunted down...

**Comment by brollb** [comment]
This hasn't been an issue for awhile. I am going to close this and we can just re-open if it shows up again.
