### ISSUE TITLE
weekend crash. high ram usage, resource monitoring?

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2277]
with a handful of the memory usage for the node process was at around 1.6G pinning the CPU at 100%. I'm not sure pm2 limits the CPU in any way or not.

it might be worthwhile to setup `sysstat` to help collect and analyze historical system activity report 

- [ ] look at pm2 cluster mode

I'll log some information here for future use
```
2018-11-17T18:40:48.201Z netsblox::error user has no project!
2018-11-17T18:40:48.201Z netsblox::error Trying to send edit msg w/o project _netsblox1542411678
```
```
2018-11-17T18:39:51.971Z netsblox::error {"type":"message","dstId":"others in room","srcId":"Player1@Shooter Better ish@userss","msgType":"Player1","content":{"Dir":82,"Y":130,"X":-190},"projectId":"5bef6c0e3596fa4"} threw exception Error: No source project found: null
2018-11-17T18:39:51.971Z netsblox::error {"type":"message","dstId":"others in room","srcId":"Player1@Shooter Better ish@userss","msgType":"Player1","content":{"Dir":56,"Y":130,"X":-190},"projectId":"5bef6c0e3596fa48"} threw exception Error: No source project found: null
2018-11-17T18:39:51.971Z netsblox::error {"type":"message","dstId":"others in room","srcId":"Player1@Shooter Better ish@userss","msgType":"Player1","content":{"Dir":82,"Y":130,"X":-190},"projectId":"5bef6c0e3596fa"} threw exception Error: No source project found: null
```

```
2018-11-17T18:41:13.390Z netsblox::trace received "{"type":"set-uuid","clientId":"_netsblox1542476156621","projectId":"fa48ed79c904"}" message from undefined (undefined)
2018-11-17T18:41:13.391Z netsblox::trace Sending message to _netsblox1542476156621 "{"type":"connected"}"
2018-11-17T18:41:13.392Z netsblox::trace received "{"type":"set-uuid","clientId":"_netsblox1542475819876","projectId":"5a0ea73404"}" message from undefined (undefined)
```

edit: a single student was sending 100 msgs/second on average
[testers.zip](https://github.com/NetsBlox/NetsBlox/files/2663823/testers.zip)

**Comment by hamidzr** [comment]
after profiling and some stress testing: the issue is from mongo getting overwhelmed with queries. looks like it is partly due to calls to `ProjectStorgae.getRawProjectById` are causing this. 

during the same period, ram and CPU usage go up and then comes back down after
mongo shows a lot of "queries" follow by a spike in "updates"

below is the stats for 5 users each issues a 1000 msgs (targeting everyone in the room, same project).
![deepinscreenshot_select-area_20181206134958](https://user-images.githubusercontent.com/12127420/49608338-fefbf500-f95d-11e8-974f-5cb0ae223c5a.png)
![deepinscreenshot_select-area_20181206135112](https://user-images.githubusercontent.com/12127420/49608396-2eaafd00-f95e-11e8-8375-2215188b78ff.png)

**Comment by hamidzr** [comment]
```
[ERROR] Trace: getting raw proj
    at Project.getRawProject (netsblox/src/server/storage/projects.js:71:21)
    at Project.getRecordStartTimes (netsblox/src/server/storage/projects.js:485:25)
    at Project.getLatestRecordStartTime (netsblox/src/server/storage/projects.js:490:25)
    at Project.isRecordingMessages (netsblox/src/server/storage/projects.js:495:25)
    at Projects.getById.then.project (netsblox/src/server/client.js:334:36)
    at _fulfilled (netsblox/node_modules/q/q.js:854:54)
    at netsblox/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (netsblox/node_modules/q/q.js:816:13)
    at netsblox/node_modules/q/q.js:624:44
    at runSingle (/home/hmd/pr
```

**Comment by hamidzr** [comment]
40k msgs. 6min. after some caching => 15 sec (70% related to log statements)

**Comment by hamidzr** [comment]
consuming 100msgs on a single handler on a client takes 10seconds
but output rate is much higher
