### ISSUE TITLE
missing keyvalue store put and get basic tests

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2295]
calls to the mocked version of the service do not work and the call trace isn't helpful
```
     TypeError: Cannot read property 'get' of undefined
      at Object.Storage.get (src/server/rpc/storage.js:1:3055)
      at getStore (src/server/rpc/procedures/key-value-store/key-value-store.js:1:14429)
      at Object.KeyValueStore.put (src/server/rpc/procedures/key-value-store/key-value-store.js:1:16831)
      at MockRPC.(anonymous function) [as put] (test/assets/mock-rpc.js:86:32)
      at Context.<anonymous> (test/unit/server/rpc/procedures/key-value-store.spec.js:29:21)
      at process.topLevelDomainCallback (domain.js:121:23)

```

**Comment by brollb** [comment]
Fixed as of #2704
