### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2313]
```
RangeError: Max payload size exceeded
    at Receiver.haveLength (/home/ubuntu/netsblox/node_modules/ws/lib/receiver.js:286:16)
    at Receiver.getPayloadLength64 (/home/ubuntu/netsblox/node_modules/ws/lib/receiver.js:272:17)
    at Receiver.startLoop (/home/ubuntu/netsblox/node_modules/ws/lib/receiver.js:127:22)
    at Receiver._write (/home/ubuntu/netsblox/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at Socket.socketOnData (/home/ubuntu/netsblox/node_modules/ws/lib/websocket.js:795:35)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by hamidzr** [comment]
```
2019-01-10T15:16:50.908Z netsblox:network-topology:error Could not find socket: _netsblox1547057818189
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'roles' of null
    at Projects.getRawProjectById.then.metadata (/home/ubuntu/netsblox/src/server/network-topology.js:82:46)
    at _fulfilled (/home/ubuntu/netsblox/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/ubuntu/netsblox/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/netsblox/node_modules/q/q.js:816:13)
    at /home/ubuntu/netsblox/node_modules/q/q.js:624:44
    at runSingle (/home/ubuntu/netsblox/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/netsblox/node_modules/q/q.js:125:13)
    at args.(anonymous function) (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by hamidzr** [comment]
```
RangeError: Attempt to write outside buffer bounds
    at Buffer.write (buffer.js:881:13)
    at serializeString (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:35:14)
    at serializeInto (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:710:17)
    at serializeObject (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/ubuntu/netsblox/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at BSON.serialize (/home/ubuntu/netsblox/node_modules/bson/lib/bson/bson.js:63:28)
    at Query.toBin (/home/ubuntu/netsblox/node_modules/mongodb-core/lib/connection/commands.js:146:25)
    at serializeCommands (/home/ubuntu/netsblox/node_modules/mongodb-core/lib/connection/pool.js:1045:43)
    at Pool.write (/home/ubuntu/netsblox/node_modules/mongodb-core/lib/connection/pool.js:1261:3)
    at executeWrite (/home/ubuntu/netsblox/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:147:10)
    at WireProtocol.insert (/home/ubuntu/netsblox/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:158:3)
    at Server.insert (/home/ubuntu/netsblox/node_modules/mongodb-core/lib/topologies/server.js:815:35)
    at Server.insert (/home/ubuntu/netsblox/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
    at insertDocuments (/home/ubuntu/netsblox/node_modules/mongodb/lib/operations/collection_ops.js:838:19)
    at save (/home/ubuntu/netsblox/node_modules/mongodb/lib/operations/collection_ops.js:1301:3)
    at /home/ubuntu/netsblox/node_modules/mongodb/lib/utils.js:437:24
    at new Promise (<anonymous>)
    at executeOperation (/home/ubuntu/netsblox/node_modules/mongodb/lib/utils.js:432:10)
    at Collection.<anonymous> (/home/ubuntu/netsblox/node_modules/mongodb/lib/collection.js:963:10)
    at Collection.deprecated [as save] (internal/util.js:47:15)
    at preprocess.then (/home/ubuntu/netsblox/src/server/storage/user-actions.js:41:49)
    at _fulfilled (/home/ubuntu/netsblox/node_modules/q/q.js:854:54)
   ¦ at _fulfilled (/home/ubuntu/netsblox/node_modules/q/q.js:854:54) 

29 2019-01-10T20:44:36.409Z netsblox:storage:project-actions:error Could not save action {"type":"user-action","action":{"type":"addSound","args":["<sound        collabId=\"item_4505\" name=\"Fahrstuhl - Musik\" sound=\"data:audio/mpeg;base64,                                                                              SUQzAwAAAABXdkNPTU0AAAAhAAAAZW5nAGNvbnZlcnRlZCBieSBjb252ZXJ0Mm1wMy5uZXRUSVQyAAAABg.....
```

**Comment by hamidzr** [comment]
```
2019-01-16T19:54:30.532Z netsblox:storage:projects:error Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/home/ubuntu/netsblox/node_modules/bson/lib/bson/objectid.js:57:11)
    at ObjectID (/home/ubuntu/netsblox/node_modules/bson/lib/bson/objectid.js:38:43)
    at Object.ProjectStorage.getRawProjectById (/home/ubuntu/netsblox/src/server/storage/projects.js:654:43)
    at Object.ProjectStorage.getById (/home/ubuntu/netsblox/src/server/storage/projects.js:639:31)
    at Handler.setUserAndId.then (/home/ubuntu/netsblox/src/server/routes/basic-routes.js:151:38)
    at _fulfilled (/home/ubuntu/netsblox/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/ubuntu/netsblox/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/netsblox/node_modules/q/q.js:816:13)
    at /home/ubuntu/netsblox/node_modules/q/q.js:624:44
    at runSingle (/home/ubuntu/netsblox/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/netsblox/node_modules/q/q.js:125:13)
    at args.(anonymous function) (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by hamidzr** [comment]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Message failed: 554 Message rejected: Stream is more than 10485760 bytes long.
    at SMTPConnection._formatError (/home/ubuntu/netsblox/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._actionSMTPStream (/home/ubuntu/netsblox/node_modules/smtp-connection/lib/smtp-connection.js:1358:30)
    at SMTPConnection.<anonymous> (/home/ubuntu/netsblox/node_modules/smtp-connection/lib/smtp-connection.js:854:18)
    at SMTPConnection._processResponse (/home/ubuntu/netsblox/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
    at SMTPConnection._onData (/home/ubuntu/netsblox/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:597:20)
```

**Comment by hamidzr** [comment]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at Object.hasLongerLines (/home/ubuntu/netsblox/node_modules/libmime/lib/libmime.js:36:65)
    at MimeNode.setContent (/home/ubuntu/netsblox/node_modules/buildmail/lib/buildmail.js:377:42)
    at MailComposer._createContentNode (/home/ubuntu/netsblox/node_modules/mailcomposer/lib/mailcomposer.js:461:14)
    at MailComposer.<anonymous> (/home/ubuntu/netsblox/node_modules/mailcomposer/lib/mailcomposer.js:324:18)
    at Array.forEach (<anonymous>)
    at MailComposer._createMixed (/home/ubuntu/netsblox/node_modules/mailcomposer/lib/mailcomposer.js:321:107)
    at MailComposer.compile (/home/ubuntu/netsblox/node_modules/mailcomposer/lib/mailcomposer.js:45:29)
    at module.exports (/home/ubuntu/netsblox/node_modules/mailcomposer/lib/mailcomposer.js:7:35)
    at Nodemailer.<anonymous> (/home/ubuntu/netsblox/node_modules/nodemailer/lib/nodemailer.js:286:24)
    at Nodemailer._processPlugins (/home/ubuntu/netsblox/node_modules/nodemailer/lib/nodemailer.js:352:16)
    at Nodemailer.sendMail (/home/ubuntu/netsblox/node_modules/nodemailer/lib/nodemailer.js:280:10)
    at Object.sendMail (/home/ubuntu/netsblox/src/server/mailer.js:38:28)
    at BugReporter.reportBug (/home/ubuntu/netsblox/src/server/bug-reporter.js:171:23)
    at getUserEmail.then.then.roomState (/home/ubuntu/netsblox/src/server/bug-reporter.js:115:25)
    at _fulfilled (/home/ubuntu/netsblox/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/ubuntu/netsblox/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/netsblox/node_modules/q/q.js:816:13)
    at /home/ubuntu/netsblox/node_modules/q/q.js:624:44
    at runSingle (/home/ubuntu/netsblox/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/netsblox/node_modules/q/q.js:125:13)
    at args.(anonymous function) (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

```

**Comment by brollb** [comment]
I think this has been resolved.
