### ISSUE TITLE
missing request for incoming project-response

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2320]
```
Failed to parse socket message: 
TypeError: Cannot read property 'roleId' of undefined

at Client.project-response (/home/ubuntu/netsblox/src/server/client.js:408:21)
at Client.onMessage (/home/ubuntu/netsblox/src/server/client.js:161:51)
at WebSocket._socket.on.data (/home/ubuntu/netsblox/src/server/client.js:115:29)
at emitOne (events.js:116:13)
at WebSocket.emit (events.js:211:7
```

**Comment by hamidzr** [comment]
https://github.com/NetsBlox/NetsBlox/pull/2321
