### ISSUE TITLE
Better error handling when receiving invalid project

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3489]
```
04.26 14:20:18 netsblox:network-topology:_netsblox1682518656978:trace > Error w/ request: Invalid address: myRole@4-2-3 Messaging@oscarf92541 from 64469295c0613000147559fb
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: Project not found: null
    at Client.saveMessage (/netsblox/src/server/client.js:350:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.onMessage (/netsblox/src/server/client.js:180:17) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}

Node.js v18.12.1
```

**Comment by brollb** [comment]
No longer an issue with the new server
